name: Python CI + Docker 

on: 
    push: 
        branches: [main, develop, feature/*]
        paths: ["python/**"]
    pull_request:
        branches: [main, develop]
        paths: ["python/**"]

jobs: 
    build_test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./python 

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.13"

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Run Ruff linter  
              run: ruff check

            - name: Run tests  
              run: PYTHONPATH=. pytest tests/

build-and-push:
    runs-on: ubuntu-latest
    needs: build_test 

    if: github.event_name == 'push'

    steps: 

        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-actions@v3
          
        - name: Log in to DockerHub
          uses: docker/login-actions@v3
          with:
            registry: docker.io
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ screts.DOCKERHUB_TOKEN }}

        - name: Build and push Docker image    
          uses: docker/build-push-actions@v5
          with: 
            context: ./python
            push: true
            tags: |
              docker.io/${{ secrets.DOCKERHUB_USERNAME }}/myflaskapp:latest
              docker.io/${{ secrets.DOCKERHUB_USERNAME }}/myflaskapp:${{ github.sha }}

