apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akv-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: flask-keyvault
    tenantId: <your-tenant-id>
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
  secretObjects:
    - secretName: db-pass-secret
      type: Opaque
      data:
        - objectName: db-password
          key: db-password
